### PR TITLE
Sonph history request detail

### PR DESCRIPTION
**Pull request by huynhkimtri**
TRIHK - merge sonph_history_requestDetail to develop

### CODE REVIEW

**Comment by huynhkimtri** [comment]
So many conflicts here :(

**Comment by huynhkimtri** [comment]
But I think I can control everything

**Comment by sonph63195** [comment]
Did you fix it?

**Comment by huynhkimtri** [comment]
> Did you fix it?

yes, still woking...

**Comment by huynhkimtri** [comment]
> Did you fix it?

I have done it already :D @sonph63195

**Pull request merged**
